---
apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: sample-db-operators
  namespace: openshift-marketplace
spec:
  sourceType: grpc
  image: quay.io/redhat-developer/sample-db-operators-olm:v1
  displayName: Sample DB Operators